name: Continuous Integration
on: [push]                      

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v4 

    - name: Hello world       # Name of step
      run: echo 'Hello world' # Command to run

    - name: Build C#/.Net code       # Name of step
      run: dotnet build

    - name: Install JS Dependencies     # Name of step
      run: npm install
      working-directory: DotnetTemplate.Web